on:
  push:
  pull_request:

name: check_code

jobs:
  check_code:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Run the script :-)
        run: Rscript r_script.R

