on:
  push:
  pull_request:

name: run_script

jobs:
  run_script:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          install.packages("testthat")
        shell: Rscript {0}

      - name: Run the script :-)
        run: Rscript r_script.R

