on:
  push:
  pull_request:

name: check_style

jobs:
  check_style:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          install.packages("lintr")
        shell: Rscript {0}

      - name: Check for style
        run: Rscript -e 'lintr::lint("r_script.R")'

